# Generated by Django 2.2.2 on 2021-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='mediamedia'),
        ),
    ]
