# Generated by Django 2.2.2 on 2021-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
