# Generated by Django 2.2.2 on 2021-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211122_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
